icons = "none"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#231f3e"
idle_fg = "#ffffff"
warning_bg = "#ff9f57"
info_bg = "#231f3e"

[[block]]
block = "custom"
command = "layout=$(swaymsg -t get_inputs | jq -M '.[2].xkb_active_layout_name'); layout=\"${layout#?}\"; layout=\"${layout%?}\"; echo \"$layout\""
interval = 1

[[block]]
block = "keyboard_layout"
interval = 1
driver = "setxkbmap"
#driver = "sway"
#sway_kb_identifier = "16700:8467:Dell_KB216_Wired_Keyboard_Consumer_Control"

[[block]]
block = "backlight"

[[block]]
block = "sound"
on_click = "amixer set Master toggle"

[[block]]
block = "networkmanager"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home/pelegs"
alias = "~/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
#format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
info = 0

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}C"
chip = "*-isa-*"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
format = "%a %Y-%m-%d %H:%M:%S"
interval = 1
